import AppKit
import CryptoKit
import Foundation
import SwiftData
import UniformTypeIdentifiers

enum ClipboardCaptureError: LocalizedError {
    case tooLarge(Int)
    case noSupportedContent

    var errorDescription: String? {
        switch self {
        case let .tooLarge(bytes):
            "剪贴内容过大（\(ByteCountFormatter.string(fromByteCount: Int64(bytes), countStyle: .file))）"
        case .noSupportedContent:
            "没有可保存的剪贴内容"
        }
    }
}

enum PrivacyFilter {
    static let privatePasteboardTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "com.apple.is-remote-clipboard"
    ]

    static func shouldIgnore(
        pasteboard: NSPasteboard,
        sourceBundleIdentifier: String?,
        excludedBundleIdentifiers: Set<String>
    ) -> Bool {
        if let sourceBundleIdentifier,
           excludedBundleIdentifiers.contains(sourceBundleIdentifier) {
            return true
        }
        let currentTypes = Set(pasteboard.types?.map(\.rawValue) ?? [])
        return !currentTypes.isDisjoint(with: privatePasteboardTypes)
    }
}

extension ClipboardPayload {
    static let maximumSearchableCharacters = 20_000

    static let imageTypes: Set<String> = [
        UTType.png.identifier,
        UTType.tiff.identifier,
        UTType.jpeg.identifier,
        UTType.heic.identifier,
        UTType.gif.identifier,
        UTType.webP.identifier
    ]

    static let supportedTypes: Set<String> = imageTypes.union([
        NSPasteboard.PasteboardType.string.rawValue,
        NSPasteboard.PasteboardType.rtf.rawValue,
        NSPasteboard.PasteboardType.rtfd.rawValue,
        NSPasteboard.PasteboardType.html.rawValue,
        NSPasteboard.PasteboardType.URL.rawValue,
        NSPasteboard.PasteboardType.fileURL.rawValue,
        NSPasteboard.PasteboardType.pdf.rawValue,
        "NSColorPboardType",
        "com.apple.flat-rtfd",
        "public.utf8-plain-text",
        "public.utf16-external-plain-text"
    ])

    static func capture(
        from pasteboard: NSPasteboard,
        maximumBytes: Int = 100 * 1_024 * 1_024
    ) throws -> CapturedClipboardContent {
        guard let sourceItems = pasteboard.pasteboardItems, !sourceItems.isEmpty else {
            throw ClipboardCaptureError.noSupportedContent
        }

        var payloadItems: [ClipboardPayloadItem] = []
        var totalBytes = 0

        for sourceItem in sourceItems {
            var representations: [ClipboardRepresentation] = []
            for type in sourceItem.types where supportedTypes.contains(type.rawValue) {
                let data: Data?
                if let existing = sourceItem.data(forType: type) {
                    data = existing
                } else if let string = sourceItem.string(forType: type) {
                    data = string.data(using: .utf8)
                } else {
                    data = nil
                }

                guard let data, !data.isEmpty else { continue }
                totalBytes += data.count
                if totalBytes > maximumBytes {
                    throw ClipboardCaptureError.tooLarge(totalBytes)
                }
                representations.append(.init(type: type.rawValue, data: data))
            }
            if !representations.isEmpty {
                payloadItems.append(.init(representations: representations))
            }
        }

        guard !payloadItems.isEmpty else {
            throw ClipboardCaptureError.noSupportedContent
        }

        let payload = ClipboardPayload(items: payloadItems)
        let payloadData = try payload.encoded()
        let digest = SHA256.hash(data: payloadData).map { String(format: "%02x", $0) }.joined()
        let classification = classify(items: payloadItems)

        return CapturedClipboardContent(
            payload: payload,
            kind: classification.kind,
            title: classification.title,
            searchableText: classification.searchableText,
            thumbnailData: classification.thumbnailData,
            fingerprint: digest
        )
    }

    fileprivate static func classify(items: [ClipboardPayloadItem]) -> (
        kind: ClipboardContentKind,
        title: String,
        searchableText: String,
        thumbnailData: Data?
    ) {
        let representations = items.flatMap(\.representations)
        let rawTypes = Set(representations.map(\.type))

        if rawTypes.contains(NSPasteboard.PasteboardType.fileURL.rawValue) {
            let fileNames = representations
                .filter { $0.type == NSPasteboard.PasteboardType.fileURL.rawValue }
                .compactMap { String(data: $0.data, encoding: .utf8) }
                .compactMap { URL(string: $0)?.lastPathComponent }
            let title = fileNames.first ?? (items.count > 1 ? "\(items.count) 个文件" : "文件")
            return (.file, title, limitedSearchText(fileNames.joined(separator: " ")), nil)
        }

        if let imageRepresentation = representations.first(where: {
            imageTypes.contains($0.type)
        }), let image = NSImage(data: imageRepresentation.data) {
            let sizeText = "\(Int(image.size.width)) × \(Int(image.size.height))"
            return (.image, "图片 \(sizeText)", sizeText, thumbnailData(for: image))
        }

        if let urlString = stringValue(in: representations, types: [
            NSPasteboard.PasteboardType.URL.rawValue
        ]), let url = URL(string: urlString.trimmingCharacters(in: .whitespacesAndNewlines)) {
            let title = url.host(percentEncoded: false) ?? url.absoluteString
            return (.link, title, limitedSearchText(url.absoluteString), nil)
        }

        if let text = stringValue(in: representations, types: [
            NSPasteboard.PasteboardType.string.rawValue,
            "public.utf8-plain-text",
            "public.utf16-external-plain-text"
        ]) {
            let clean = text.trimmingCharacters(in: .whitespacesAndNewlines)
            if let url = standaloneURL(in: clean) {
                let title = url.host(percentEncoded: false) ?? String(clean.prefix(80))
                return (.link, title, limitedSearchText(clean), nil)
            }
            let firstLine = clean.split(whereSeparator: \.isNewline).first.map(String.init) ?? "文本"
            let title = String(firstLine.prefix(80))
            let kind: ClipboardContentKind = rawTypes.contains(NSPasteboard.PasteboardType.rtf.rawValue) ||
                rawTypes.contains(NSPasteboard.PasteboardType.html.rawValue) ||
                clean.contains(where: \.isNewline) ? .richText : .text
            return (kind, title.isEmpty ? kind.displayName : title, limitedSearchText(clean), nil)
        }

        if rawTypes.contains("NSColorPboardType") {
            return (.color, "颜色", "颜色", nil)
        }

        return (.unknown, "剪贴内容", rawTypes.sorted().joined(separator: " "), nil)
    }

    private static func limitedSearchText(_ text: String) -> String {
        String(text.prefix(maximumSearchableCharacters))
    }

    private static func standaloneURL(in text: String) -> URL? {
        guard !text.isEmpty, !text.contains(where: \.isWhitespace) else { return nil }
        guard let separator = text.firstIndex(of: ":") else { return nil }
        let scheme = text[..<separator].lowercased()
        let remainder = text[text.index(after: separator)...]
        guard remainder.hasPrefix("//") || ["mailto", "tel"].contains(scheme) else { return nil }
        return URL(string: text)
    }

    private static func stringValue(
        in representations: [ClipboardRepresentation],
        types: [String]
    ) -> String? {
        for type in types {
            guard let representation = representations.first(where: { $0.type == type }) else { continue }
            if let string = String(data: representation.data, encoding: .utf8) {
                return string
            }
            if let string = String(data: representation.data, encoding: .utf16) {
                return string
            }
        }
        return nil
    }

    private static func thumbnailData(for source: NSImage) -> Data? {
        let maxSize = NSSize(width: 456, height: 296)
        let scale = min(maxSize.width / max(source.size.width, 1), maxSize.height / max(source.size.height, 1), 1)
        let targetSize = NSSize(width: source.size.width * scale, height: source.size.height * scale)
        let target = NSImage(size: targetSize)
        target.lockFocus()
        NSGraphicsContext.current?.imageInterpolation = .high
        source.draw(
            in: NSRect(origin: .zero, size: targetSize),
            from: NSRect(origin: .zero, size: source.size),
            operation: .copy,
            fraction: 1
        )
        target.unlockFocus()
        return target.clipboardRipplePNGData()
    }
}

@MainActor
final class PasteboardMonitor {
    var onCapture: ((CapturedClipboardContent, NSRunningApplication?) -> Void)?
    var onSkippedContent: ((String) -> Void)?
    var isPaused = false
    var excludedBundleIdentifiers: Set<String> = []

    private let pasteboard: NSPasteboard
    private var timer: Timer?
    private var lastChangeCount: Int

    init(pasteboard: NSPasteboard = .general) {
        self.pasteboard = pasteboard
        self.lastChangeCount = pasteboard.changeCount
    }

    func start() {
        guard timer == nil else { return }
        let timer = Timer(timeInterval: 0.35, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated {
                self?.poll()
            }
        }
        timer.tolerance = 0.08
        self.timer = timer
        RunLoop.main.add(timer, forMode: .common)
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    func markOwnWrite() {
        lastChangeCount = pasteboard.changeCount
    }

    private func poll() {
        let currentChangeCount = pasteboard.changeCount
        guard currentChangeCount != lastChangeCount else { return }
        lastChangeCount = currentChangeCount
        guard !isPaused else { return }

        let sourceApplication = NSWorkspace.shared.frontmostApplication
        let sourceBundleIdentifier = sourceApplication?.bundleIdentifier
        guard sourceBundleIdentifier != Bundle.main.bundleIdentifier else { return }
        guard !PrivacyFilter.shouldIgnore(
            pasteboard: pasteboard,
            sourceBundleIdentifier: sourceBundleIdentifier,
            excludedBundleIdentifiers: excludedBundleIdentifiers
        ) else { return }

        do {
            let captured = try ClipboardPayload.capture(from: pasteboard)
            onCapture?(captured, sourceApplication)
        } catch ClipboardCaptureError.noSupportedContent {
            return
        } catch {
            onSkippedContent?(error.localizedDescription)
        }
    }
}

@MainActor
final class HistoryStore {
    private static let directoryName = "ClipboardRipple"
    private static let storeName = "ClipboardRipple.store"
    private static let supportDirectoryName = ".ClipboardRipple_SUPPORT"
    private static let legacyStores: [(
        directoryName: String,
        storeName: String,
        supportDirectoryName: String
    )] = [
        ("ClipDock", "ClipDock.store", ".ClipDock_SUPPORT"),
        ("ClipDeck", "ClipDeck.store", ".ClipDeck_SUPPORT"),
    ]

    private let container: ModelContainer
    private let context: ModelContext

    init(inMemory: Bool = false, applicationSupportURL: URL? = nil) throws {
        let configuration: ModelConfiguration
        if inMemory {
            configuration = ModelConfiguration(isStoredInMemoryOnly: true)
        } else {
            let baseURL = try applicationSupportURL ?? FileManager.default.url(
                for: .applicationSupportDirectory,
                in: .userDomainMask,
                appropriateFor: nil,
                create: true
            )
            try Self.migrateLegacyStoreIfNeeded(in: baseURL)
            let directoryURL = baseURL.appendingPathComponent(Self.directoryName, isDirectory: true)
            try FileManager.default.createDirectory(
                at: directoryURL,
                withIntermediateDirectories: true
            )
            let resolvedURL = directoryURL.appendingPathComponent(Self.storeName)
            configuration = ModelConfiguration(url: resolvedURL, cloudKitDatabase: .none)
        }
        container = try ModelContainer(
            for: ClipboardRecord.self,
            PinboardRecord.self,
            configurations: configuration
        )
        context = ModelContext(container)
        context.autosaveEnabled = false
    }

    static func migrateLegacyStoreIfNeeded(
        in baseURL: URL,
        fileManager: FileManager = .default
    ) throws {
        let destination = baseURL.appendingPathComponent(directoryName, isDirectory: true)
        guard !fileManager.fileExists(atPath: destination.path) else { return }

        guard let legacy = legacyStores.first(where: { candidate in
            let directory = baseURL.appendingPathComponent(
                candidate.directoryName,
                isDirectory: true
            )
            return fileManager.fileExists(
                atPath: directory.appendingPathComponent(candidate.storeName).path
            )
        }) else { return }

        let legacyDirectory = baseURL.appendingPathComponent(
            legacy.directoryName,
            isDirectory: true
        )

        let staging = baseURL.appendingPathComponent(
            ".ClipboardRipple-migration-\(UUID().uuidString)",
            isDirectory: true
        )
        try fileManager.copyItem(at: legacyDirectory, to: staging)
        defer { try? fileManager.removeItem(at: staging) }

        for suffix in ["", "-wal", "-shm"] {
            let source = staging.appendingPathComponent(legacy.storeName + suffix)
            guard fileManager.fileExists(atPath: source.path) else { continue }
            try fileManager.moveItem(
                at: source,
                to: staging.appendingPathComponent(storeName + suffix)
            )
        }

        let legacySupport = staging.appendingPathComponent(
            legacy.supportDirectoryName,
            isDirectory: true
        )
        if fileManager.fileExists(atPath: legacySupport.path) {
            try fileManager.moveItem(
                at: legacySupport,
                to: staging.appendingPathComponent(supportDirectoryName, isDirectory: true)
            )
        }
        try fileManager.moveItem(at: staging, to: destination)
    }

    func fetchRecords() -> [ClipboardRecord] {
        let descriptor = FetchDescriptor<ClipboardRecord>(
            sortBy: [SortDescriptor(\.capturedAt, order: .reverse)]
        )
        return (try? context.fetch(descriptor)) ?? []
    }

    func fetchPinboards() -> [PinboardRecord] {
        let descriptor = FetchDescriptor<PinboardRecord>(
            sortBy: [SortDescriptor(\.createdAt)]
        )
        return (try? context.fetch(descriptor)) ?? []
    }

    @discardableResult
    func upsert(
        _ captured: CapturedClipboardContent,
        sourceApplication: NSRunningApplication?
    ) throws -> ClipboardRecord {
        let fingerprint = captured.fingerprint
        let sourceBundleIdentifier = sourceApplication?.bundleIdentifier
        let sourceApplicationName = sourceApplication?.localizedName
            ?? sourceApplication?.bundleURL?.deletingPathExtension().lastPathComponent
        let existing: ClipboardRecord?
        if captured.kind == .image {
            existing = nil
        } else {
            var descriptor = FetchDescriptor<ClipboardRecord>(
                predicate: #Predicate { $0.fingerprint == fingerprint }
            )
            descriptor.fetchLimit = 1
            existing = try context.fetch(descriptor).first
        }

        let record: ClipboardRecord
        if let existing {
            existing.capturedAt = Date()
            existing.title = captured.title
            existing.kindRawValue = captured.kind.rawValue
            existing.searchableText = captured.searchableText
            existing.sourceBundleIdentifier = sourceBundleIdentifier
            existing.sourceApplicationName = sourceApplicationName
            existing.payloadData = try captured.payload.encoded()
            existing.thumbnailData = captured.thumbnailData
            record = existing
        } else {
            record = ClipboardRecord(
                title: captured.title,
                kind: captured.kind,
                searchableText: captured.searchableText,
                fingerprint: fingerprint,
                sourceBundleIdentifier: sourceBundleIdentifier,
                sourceApplicationName: sourceApplicationName,
                payloadData: try captured.payload.encoded(),
                thumbnailData: captured.thumbnailData
            )
            context.insert(record)
        }
        try context.save()
        return record
    }

    func delete(_ record: ClipboardRecord) throws {
        context.delete(record)
        try context.save()
    }

    func save() throws {
        try context.save()
    }

    func createPinboard(name: String, colorHex: String) throws {
        context.insert(PinboardRecord(name: name, colorHex: colorHex))
        try context.save()
    }

    func deletePinboard(_ pinboard: PinboardRecord) throws {
        for record in fetchRecords() where record.pinboardIDs.contains(pinboard.id) {
            record.pinboardIDs.removeAll { $0 == pinboard.id }
        }
        context.delete(pinboard)
        try context.save()
    }

    func cleanup(retentionDays: Int, now: Date = Date()) throws {
        let clampedDays = min(max(retentionDays, 1), 30)
        guard let cutoff = Calendar.current.date(byAdding: .day, value: -clampedDays, to: now) else { return }
        let descriptor = FetchDescriptor<ClipboardRecord>(
            predicate: #Predicate { $0.capturedAt < cutoff }
        )
        for record in try context.fetch(descriptor) where !record.isPinned {
            context.delete(record)
        }
        try context.save()
    }

    func clearUnpinnedHistory() throws {
        for record in fetchRecords() where !record.isPinned {
            context.delete(record)
        }
        try context.save()
    }

    func compactSearchableText() throws {
        var changed = false
        for record in fetchRecords()
        where record.searchableText.count > ClipboardPayload.maximumSearchableCharacters {
            record.searchableText = String(
                record.searchableText.prefix(ClipboardPayload.maximumSearchableCharacters)
            )
            changed = true
        }
        if changed { try context.save() }
    }

    @discardableResult
    func reclassifyLegacyLinks() throws -> Int {
        var repaired = 0
        for record in fetchRecords() where record.kind == .link {
            guard let payload = record.payload else { continue }
            let classification = ClipboardPayload.classify(items: payload.items)
            guard classification.kind != .link else { continue }
            record.kindRawValue = classification.kind.rawValue
            record.title = classification.title
            record.searchableText = classification.searchableText
            record.thumbnailData = classification.thumbnailData
            repaired += 1
        }
        if repaired > 0 { try context.save() }
        return repaired
    }
}
